language: python
python:
    - "3.4"

before_script:
    - sleep 10

before_install:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"

install: 
    - "pip install -r requirements_dev.txt"

script:
    - "flake8 ."
    - "py.test"

